import { useState } from 'react';
import { Check, Copy, Download, Loader2, ShieldAlert, Sparkles } from 'lucide-react';
import Modal from './Modal';
import { API_BASE, ApiError, getSkillCredentials } from '../lib/api';
import { buildSkillZip, loadSkillFiles, renderCredentials, triggerDownload } from '../lib/skillBundle';
import { useToast } from '../hooks/useToast';

const EXAMPLES = [
    { label: 'Generate a month', text: 'Generate the October 2026 roster for TS - Mission. Here are the leave requests from Slack: <paste thread>. Keep the weekend and night-shift rules from the team prompt.' },
    { label: 'Move someone to another team', text: 'Move Ayush Raina from ACE to TS - Payments effective 1 November 2026. Keep his October roster under ACE.' },
    { label: 'Mark planned leave', text: 'Mark PL for Sanjayan in TS - PSE Support on 14 and 15 October 2026 and tell me who covers the weekend.' },
    { label: 'Who is on call', text: 'Who is on call this Sunday across all teams, and who is on the night shift next week for TS - Mission?' },
];

function CopyButton({ text }) {
    const [copied, setCopied] = useState(false);
    const copy = async () => {
        try {
            await navigator.clipboard.writeText(text);
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
        } catch { /* clipboard blocked: the text is visible to select manually */ }
    };
    return (
        <button type="button" className="icon-btn icon-btn-sm" onClick={copy} aria-label={copied ? 'Copied' : 'Copy prompt'} title="Copy">
            {copied ? <Check size={14} className="text-accent" /> : <Copy size={14} />}
        </button>
    );
}

/** Explains the Claude-based generation flow and downloads a ready-to-use skill bundle. */
export default function ClaudeSkillModal({ open, onClose, me, features }) {
    const toast = useToast();
    const [busy, setBusy] = useState(false);
    const canHaveKey = !!me?.isAdmin;

    const download = async () => {
        setBusy(true);
        try {
            let creds = null;
            if (features?.skillCredentials !== false) {
                try {
                    creds = await getSkillCredentials();
                } catch (err) {
                    if (!(err instanceof ApiError && err.status === 404)) throw err;
                }
            }
            const [{ default: JSZip }, { manifest, files }] = await Promise.all([
                import('jszip'),
                loadSkillFiles(import.meta.env.BASE_URL),
            ]);
            const credentialsText = renderCredentials(creds || {}, { email: me?.email, apiBase: API_BASE });
            const blob = await buildSkillZip(JSZip, {
                files,
                credentialsPath: manifest.credentials_file || 'roster-manager/references/credentials.md',
                credentialsText,
            });
            triggerDownload(blob, 'roster-manager-skill.zip');
            toast.success(creds?.service_key ? 'Skill downloaded with your write key — keep the zip private' : 'Skill downloaded (read-only credentials)');
        } catch (err) {
            toast.error(err.message || 'Could not build the skill bundle');
        } finally {
            setBusy(false);
        }
    };

    return (
        <Modal
            open={open}
            onClose={onClose}
            title="Generate with Claude"
            subtitle="Rosters are generated by chatting with Claude Code"
            icon={<Sparkles size={20} />}
            size="md"
            busy={busy}
            footer={(
                <>
                    <button type="button" className="btn btn-secondary" onClick={onClose} disabled={busy}>Close</button>
                    <button type="button" className="btn btn-primary" onClick={download} disabled={busy} data-autofocus>
                        {busy ? <Loader2 size={16} className="spin" aria-hidden="true" /> : <Download size={16} aria-hidden="true" />}
                        Download roster-manager skill (.zip)
                    </button>
                </>
            )}
        >
            <div className="stack">
                <p className="modal-text">
                    Rosters are generated with Claude Code using the <strong>roster-manager</strong> skill: paste the Slack thread, Claude builds,
                    validates and saves the month through the Roster API, and tells you exactly what changed.
                </p>

                <ol className="steps">
                    <li><span className="strong">Install Claude Code</span> — <code>npm install -g @anthropic-ai/claude-code</code> (or the desktop app).</li>
                    <li><span className="strong">Download the skill</span> with the button below. The zip includes credentials generated for you.</li>
                    <li><span className="strong">Unzip it</span> into your project's <code>.claude/skills/</code> folder, so you end up with <code>.claude/skills/roster-manager/SKILL.md</code>.</li>
                    <li><span className="strong">Open Claude Code there and ask</span>, e.g. <em>“Generate the October 2026 roster for TS - Mission, here are the leave requests: …”</em>.</li>
                </ol>

                <div>
                    <div className="field-label">Example prompts</div>
                    <ul className="list prompt-examples">
                        {EXAMPLES.map((ex) => (
                            <li key={ex.label} className="list-row">
                                <div>
                                    <div className="small strong">{ex.label}</div>
                                    <div className="small muted">{ex.text}</div>
                                </div>
                                <CopyButton text={ex.text} />
                            </li>
                        ))}
                    </ul>
                </div>

                {canHaveKey ? (
                    <div className="banner banner-warning" role="note">
                        <ShieldAlert size={16} aria-hidden="true" />
                        <div className="banner-text">You are an admin, so the zip contains a <strong>write key</strong> that lets Claude change rosters. Keep it private and do not commit it.</div>
                    </div>
                ) : (
                    <p className="muted small">Your bundle contains read-only credentials. Ask a roster admin for a write key if Claude should save changes.</p>
                )}
            </div>
        </Modal>
    );
}
